repos:
  - hooks:
      - args:
          - --multi-line=3
          - --trailing-comma
          - --force-grid-wrap=0
          - --use-parentheses
          - --line-width=88
          - --ensure-newline-before-comments
        id: isort
    repo: https://github.com/pycqa/isort
    rev: 5.13.2
  - hooks:
      - args:
          - --max-line-length=89
          - --max-complexity=15
          - --extend-ignore=E203
        id: flake8
    repo: https://github.com/pycqa/flake8
    rev: 7.0.0
  - hooks:
      - args:
          - --py36-plus
        id: pyupgrade
    repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: 24.4.2
  - hooks:
      - additional_dependencies:
          - types-attrs
          - types-requests
          - types-setuptools
          - types-PyYAML
          - types-toml
        args:
          - --ignore-missing-imports
          - --no-implicit-optional
        id: mypy
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
  - hooks:
      - args:
          - --convention=google
          - --add-ignore=D104
        id: pydocstyle
    repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
  - hooks:
      - id: blacken-docs
    repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-case-conflict
      - id: check-json
      - id: check-added-large-files
      - id: check-yaml
      - id: mixed-line-ending
      - id: check-toml
      - id: pretty-format-json
      - id: check-docstring-first
      - id: check-symlinks
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
  - hooks:
      - args:
          - -iii
          - -lll
        id: bandit
    repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
  - hooks:
      - additional_dependencies:
          - radon
        args:
          - cc
          - --min=C
          - --total-average
        entry: radon
        id: radon
        language: python
        name: radon
        verbose: true
    repo: local
  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.25.1
