services:
  pipelines:
    image: chimefrb/pipelines:latest
    container_name: pipelines
    command: python -m pipelines.server
    platform: linux/amd64
    ports:
      - "8001:8001"
    expose:
      - 8001
    environment:
      - SANIC_HOSTNAME=0.0.0.0
      - SANIC_PORT=8001
      - SANIC_ACCESS_LOG=true
      - SANIC_AUTO_RELOAD=true
      - SANIC_DEBUG=true
      - SANIC_MONGODB_HOSTNAME=mongo
      - SANIC_MONGODB_PORT=27017
      - SANIC_START_MANAGER_URL=http://managers:8002/v2/start
      - SANIC_PAUSE_MANAGER_URL=http://managers:8002/v2/pause
      - SANIC_STOP_MANAGER_URL=http://managers:8002/v2/stop
      - SANIC_HEALTH_MANAGERS_URL=http://managers:8002/__health__
      - SANIC_HEALTH_MANAGERS_CHECK_TIMES=10
      - SANIC_HEALTH_MANAGERS_CHECK_INTERVAL_SECONDS=30
      - SANIC_LISTENERS_THRESHOLD_SECONDS=120
      - TZ=Etc/UTC
    networks:
      - workflow

  managers:
    image: chimefrb/pipelines:latest
    container_name: managers
    command: ["/bin/bash", "-c", "python -m managers.server"]
    platform: linux/amd64
    ports:
      - "8002:8002"
    environment:
      - SANIC_HOSTNAME=0.0.0.0
      - SANIC_PORT=8002
      - SANIC_ACCESS_LOG=true
      - SANIC_AUTO_RELOAD=true
      - SANIC_DEBUG=true
      - SANIC_MONGODB_HOSTNAME=mongo
      - SANIC_MONGODB_PORT=27017
      - SANIC_BUCKETS_URL=http://buckets:8004
      - SANIC_RESULTS_URL=http://results:8005
      - SANIC_UPDATE_INTERVAL_SECONDS=40
      - SANIC_SLEEP_INTERVAL_SECONDS=30
      - SANIC_PURGE_TIME_SECONDS=3600
      - SANIC_DEPLOYER_REDEPLOY_WAIT_TIME=30
      - SANIC_DEPLOYER_MAX_REPLICAS=256
      - SANIC_WORKSPACE_FILEPATH=/etc/workspace.yml
      - TZ=Etc/UTC
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workflow/workspaces/development.yml:/etc/workspace.yml
    networks:
      - workflow

  buckets:
    image: chimefrb/buckets:latest
    container_name: buckets
    command: [ "/bin/bash", "-c", "python -m buckets.server" ]
    expose:
      - 8004
    ports:
      - "8004:8004"
    environment:
      - SANIC_HOSTNAME=0.0.0.0
      - SANIC_PORT=8004
      - SANIC_ACCESS_LOG=true
      - SANIC_AUTO_RELOAD=true
      - SANIC_DEBUG=true
      - SANIC_MONGODB_HOSTNAME=mongo
      - SANIC_MONGODB_PORT=27017
      - SANIC_CORS_ORIGINS=*
      - SANIC_WORKSPACE=development
    networks:
      - workflow

  results:
    image: chimefrb/results:latest
    container_name: results
    command: [ "/bin/bash", "-c", "python -m results.server" ]
    expose:
      - 8005
    ports:
      - "8005:8005"
    environment:
      - SANIC_HOSTNAME=0.0.0.0
      - SANIC_PORT=8005
      - SANIC_ACCESS_LOG=true
      - SANIC_AUTO_RELOAD=true
      - SANIC_DEBUG=true
      - SANIC_MONGODB_HOSTNAME=mongo
      - SANIC_MONGODB_PORT=27017
      - SANIC_CORS_ORIGINS=*
      - SANIC_WORKSPACE=development
    networks:
      - workflow

  mongo:
    image: mongo:latest
    command: mongod --bind_ip_all
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - workflow

networks:
  workflow:
    name: workflow
    driver: bridge
    attachable: true
