version: "3.9"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--configFile=/etc/traefik/traefik.yaml"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yaml:/etc/traefik/traefik.yaml"
      - "./traefik_docker.yaml:/etc/traefik/traefik_docker.yaml"

  authentication:
    image: authentication:local
    command: ["/bin/bash", "-c", "python -m authentication.server"]
    expose:
      - 4000
    environment:
      - DEBUG=1
      - SANIC_HOSTNAME=0.0.0.0
      - SANIC_PORT=4000
      - SANIC_ACCESS_LOG=true
      - SANIC_AUTO_RELOAD=true
      - SANIC_DEBUG=true
      - SANIC_CORS_ORIGINS=*
      - SANIC_ACCESS_URL=https://github.com/login/oauth/access_token
      - SANIC_ORGANIZATIONS_URL=https://api.github.com/user/orgs
      - SANIC_TEAMS_URL=https://api.github.com/user/teams
      - SANIC_GITHUB_ORGS_ALLOWED=CHIMEFRB,test-organization-36

  buckets:
    image: chimefrb/buckets:latest
    command: ["/bin/bash", "-c", "python -m buckets.server"]
    expose:
      - 8004
    environment:
      - SANIC_HOSTNAME=0.0.0.0
      - SANIC_PORT=8004
      - SANIC_ACCESS_LOG=true
      - SANIC_AUTO_RELOAD=true
      - SANIC_DEBUG=true
      - SANIC_MONGODB_HOSTNAME=mongo
      - SANIC_MONGODB_PORT=27017
      - SANIC_CORS_ORIGINS=*

  results:
    image: chimefrb/results:latest
    command: ["/bin/bash", "-c", "python -m results.server"]
    expose:
      - 8005
    environment:
      - SANIC_HOSTNAME=0.0.0.0
      - SANIC_PORT=8005
      - SANIC_ACCESS_LOG=true
      - SANIC_AUTO_RELOAD=true
      - SANIC_DEBUG=true
      - SANIC_MONGODB_HOSTNAME=mongo
      - SANIC_MONGODB_PORT=27017
      - SANIC_CORS_ORIGINS=*

  pipelines:
    image: chimefrb/pipelines:latest
    command: ["/bin/bash", "-c", "python -m pipelines.server"]
    expose:
      - 8006
    environment:
      - SANIC_HOSTNAME=0.0.0.0
      - SANIC_PORT=8006
      - SANIC_ACCESS_LOG=true
      - SANIC_AUTO_RELOAD=true
      - SANIC_DEBUG=true
      - SANIC_MONGODB_HOSTNAME=mongo
      - SANIC_MONGODB_PORT=27017
      - SANIC_CORS_ORIGINS=*
      - SANIC_START_MANAGER_URL=http://managers:8007/v1/start
      - SANIC_PAUSE_MANAGER_URL=http://managers:8007/v1/pause
      - SANIC_STOP_MANAGER_URL=http://managers:8007/v1/stop
      - SANIC_HEALTH_MANAGERS_URL=http://managers:8007/__health__
      - SANIC_HEALTH_MANAGERS_CHECK_TIMES=10
      - SANIC_HEALTH_MANAGERS_CHECK_INTERVAL_SECONDS=30
      - SANIC_LISTENERS_THRESHOLD_SECONDS=120

  managers:
    image: chimefrb/pipelines:latest
    command: ["/bin/bash", "-c", "python -m managers.server"]
    expose:
      - 8007
    environment:
      - SANIC_HOSTNAME=0.0.0.0
      - SANIC_PORT=8007
      - SANIC_ACCESS_LOG=true
      - SANIC_AUTO_RELOAD=true
      - SANIC_DEBUG=true
      - SANIC_MONGODB_HOSTNAME=mongo
      - SANIC_MONGODB_PORT=27017
      - SANIC_CORS_ORIGINS=*
      - SANIC_BUCKETS_URL=http://buckets:8004
      - SANIC_RESULTS_URL=http://results:8005
      - SANIC_UPDATE_INTERVAL_SECONDS=60
      - SANIC_PURGE_TIME_SECONDS=3600
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007/__health__"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo:
    image: mongo
    command: mongod --bind_ip_all
    ports:
      - "27017:27017"
