version: 1
name: example
defaults:
  user: test
  site: local

deployments:
  - name: test-deployment # Name is required
    site: canfar # Same valid sites as the work object
    image: test/test-image:latest #This is the container image
    resources:
      cores: 2 # Integer value of cores
      ram: 4G #1G, -- either MB or GB of RAMS
      gpu: 4 # Optional, int value for GPUs
    replicas: 1 #Int value

pipeline:
  # Provision top-level
  steps:
    - name: alpha
      stage: 1
      work:
        function: guidelines.example.alpha
        parameters:
          mu0: 100.1
          sigma0: 22.0
    - name: beta
      runs-on: test-deployment
      # Provision stage-level
      stage: 2
      work:
        function: guidelines.example.beta
        parameters:
          mu0: 100.1
          sigma0: 22.0
        # Teardown stage-level
    - name: gamma
      stage: 3
      work:
        function: guidelines.example.gamma
        parameters:
          mu0: 100.1
          sigma0: 22.0
  # Teardown of top-level
