entryPoints:
  web:
    address: ":80"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false
    defaultRule: "Host(`workflow.{{ normalize .Name }}`)"
    swarmMode: true
  file:
    filename: "/etc/traefik/traefik_docker.yaml"
