work:
  config:
    archive:
      enabled: true
      modes: ["pass", "copy", "move", "delete", "upload"]
    notify:
      enabled: true
      modes: ["slack"]
  sites:
    - "canfar"
    - "cedar"
    - "chime"
    - "aro"
    - "hco"
    - "gbo"
    - "kko"
    - "local"


authentication:
  enabled: true
