version: "2"
name: workflow-dev-pipeline

defaults:
  user: developer
  site: local

deployments:
  - name: small
    site: local
    image: chimefrb/workflow:latest
    sleep: 1
    resources:
      cores: 2
      ram: 1G
    replicas: 2
  - name: medium
    site: chime
    sleep: 1
    image: chimefrb/workflow:latest
    resources:
      cores: 4
      ram: 2G
    replicas: 2

pipeline:
  runs_on: small
  steps:
    - name: echo
      stage: 1
      runs_on: medium
      work:
        site: chime
        command: ["ls", "-lah"]
    - name: uname
      stage: 2
      work:
        command: ["uname", "-a"]
    - name: printenv
      stage: 3
      work:
        command: ["printenv"]
