name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
    # types:
    #   - ready_for_review
    #   - synchronize

jobs:
  pre-commit:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
    -
      name: Checking out repository
      uses: actions/checkout@v4
    -
      name: Setting up python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    -
      uses: pre-commit/action@v3.0.1

  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    needs: pre-commit
    steps:
    -
      name: Checking out repository
      uses: actions/checkout@v4
    -
      name: Installing poetry
      run: |
        pipx install poetry
    -
      name: Setting up python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.CHIMEFRB_DOCKER_USERNAME }}
        password: ${{ secrets.CHIMEFRB_DOCKER_PASSWORD }}
    -
      name: Run services
      run: |
        docker compose -f docker-compose.yml up buckets mongo results -d
        sleep 10
        docker compose -f docker-compose.yml up -d
        sleep 10
        docker compose logs
    -
      name: Run workflow tests
      run: |
        poetry install --no-cache
        poetry run workflow workspace set development
        poetry run pytest --cov workflow/ --cov-report=lcov -s -v
    -
      name: Upload coverage report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "coverage.lcov"
    -
      name: Kill services
      if: always()
      run: |
        docker compose -f docker-compose.yml down -v
